### ISSUE TITLE
Project Management tool?

### ISSUE THREAD

**Issue by Cromian** [hackshackers/action-group-website#10]
@hackshackers/action-group-website Hey everyone after todays call another idea came up. What do you think of implementing a project-management tool for committees to collaborate under? It sounds like many issues span across different teams, so it may be beneficial to bring everyone under a single tool to help move things forward? 

We use basecamp, and found it helpful in managing decentralized teams. The nice thing is that today they announced the new version that offers one free project.

https://basecamp.com 

We would still use GitHub to do our own stuff, so this would be something to help the other teams work more efficiently.

Thoughts?

**Comment by phillipadsmith** [comment]
I'm also a Basecamp user, and yet these days that's more because it's something I've used since 2008 more than my belief that it's a good tool for the job. 

For Hacks/Hackers Connect, we've been using Trello. It's also free and allows cross-team collaboration. And yet, it has its own shortcomings. 

These days, if I were starting from scratch -- as we are for this very project! -- I would attempt to convince people to use GitHub. There are many add-ons that make it very much like Basecamp and/or Trello, see: https://github.com/phillipadsmith/awesome-github#tips-tricks-tools-and-add-ons-for-github-power-users

The advantage I see in GitHub is its open and collaborative nature and culture. There are also "public" Trello boards, which are probably the next closest thing. For me, the critical ingredients to all of this are:
- Default to "open"
- Works done in public
- Allow projects to cross-reference conversations, or to-do items in another project (e.g., X question around governance relies on Y conversation around communications)

Three cents,

Phillip.

**Comment by Cromian** [comment]
@phillipadsmith ok first of all I'm calling you the Github Wizard those are some nifty tools. If we were to create a PM tool with GitHub what would that look like /  you think its something the community will use?

**Comment by thomaswilburn** [comment]
We use Trello at the Times as well, and it's fine, but it's not as good for discussion or referential conversations. I do think GitHub has a strong advantage there. We've also moved our internal documentation over to GitHub wikis, and between that and issues it's not too hard for non-technical people to use.

**Comment by phillipadsmith** [comment]
> If we were to create a PM tool with GitHub what would that look like / you think its something the community will use?

There are several out there already that are quite good, e.g.: 
https://overv.io/
https://huboard.com/
https://www.zenhub.io/

I think we can set a great example by committing to "work open," and thus making it easy for any other HH chapters/members to follow along / join the conversation / see the work in progress -- it's the open source way! :-)
